CREATE TABLE [Inventory2]
(
	[date] DATETIME NOT NULL PRIMARY KEY, 
    [prevDIp] NVARCHAR(50) NOT NULL, 
    [todayDip] NVARCHAR(50) NOT NULL, 
    [dipSale] NVARCHAR(50) NOT NULL, 
    [tankNo] NVARCHAR(50) NOT NULL
)
